THRESHOLD_DICT_BaSyTec_custom_fit_to_known_data = [  # BaSyTec
    0.002,  # ACCURACY_VOLTAGE_SIGNAL
    0.003,  # ACCURACY_CURRENT_SIGNAL
    0.002,  # ACCURACY_VOLTAGE_MEASUREMENT
    0.003,  # ACCURACY_CURRENT_MEASUREMENT
    6,  # FS_VOLTAGE
    5  # FS_CURRENT
]