threshold_dict_neware = [
    0.0005,  # ACCURACY_VOLTAGE_SIGNAL
    0.0005,  # ACCURACY_CURRENT_SIGNAL
    0.0005,  # ACCURACY_VOLTAGE_MEASUREMENT
    0.0005,  # ACCURACY_CURRENT_MEASUREMENT
    5,       # FS_VOLTAGE
    3        # FS_CURRENT
]