repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [src]
        pass_filenames: false
  - repo: local
    hooks:
      - id: test-coverage
        name: test-coverage
        entry: python -m pytest test/coverage/test_coverage_files.py -v
        language: system
        pass_filenames: false
        always_run: true
