name: CI_Commit
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
env:
  PRE_COMMIT_HOME: .cache/pre-commit

jobs:
  #------------#
  #--- LINT ---#
  #------------#
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: init
        uses: actions/checkout@v6
      - name: python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: pre-commit
        run: uv add pre-commit
      - name: ruff_linter
        run: uv run pre-commit run ruff --all-files --show-diff-on-failure
      - name: ruff_formatter
        run: uv run pre-commit run ruff-format --all-files --show-diff-on-failure

  #------------#
  #--- MYPY ---#
  #------------#
  mypy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: init
        uses: actions/checkout@v6
      - name: python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: pre-commit
        run: uv add pre-commit
      - name: mypy
        run: uv run pre-commit run mypy --all-files --show-diff-on-failure

  #------------------------#
  #--- PYTHON-VERSIONS INSTALL-CHECK --#
  #------------------------#
  install-check:
    runs-on: ubuntu-latest
    needs: mypy
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - name: init
        uses: actions/checkout@v6
      - name: python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: install
        run: uv sync --frozen

  #------------#
  #--- TEST ---#
  #------------#
  test:
    runs-on: ubuntu-latest
    needs: install-check
    steps:
      - name: init
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: tk
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk
      - name: uv_sync
        run: uv sync --frozen --group test
      - name: run_tests
        run: |
          uv run pytest -v test/api_accessible \
            -n 2 \
            --junitxml=report.xml \
            --cov=src/pydpeet \
            --cov-report=term \
            --cov-report=html:coverage_html \
            --cov-report=xml:coverage.xml \
            --reruns 5 \
            --only-rerun numpy._core._exceptions._ArrayMemoryError
      - name: test_artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            report.xml
            coverage.xml
            coverage_html/
          retention-days: 14
